version: '3'

services:
  webapi:
    build:
      context: ./BankAPI
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:80
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  database:
    # build:
    #   context: ./database
    restart: always
    ports:
      - 3306:3306
    image: mysql:8.0.35-debian
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=db_webapi
      - MYSQL_USER=webapi
      - MYSQL_PASSWORD=webapi