version: '3'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:80
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  database:
    image: mysql:8.0.35-debian
    #image: alpine
    #volumes: 
    #  - ./tds.db:/app/tds.db
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD="senharoot"
      - MYSQL_DATABASE="db_webapi"
      - MYSQL_USER="webapi"
      - MYSQL_PASSWORD="webapi"